inherit_from:
  - https://raw.githubusercontent.com/carbonfive/c5-conventions/master/rubocop/rubocop.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0.1
  SuggestExtensions: false
  Exclude:
    - db/schema.rb
    - vendor/**/*
    - bin/bundle
    - bin/rspec

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/NumericPredicate:
  Exclude:
    - app/services/workflow_instance_runner_service.rb
