version: '3'
services:
  backend:
    build: .
    ports:
      - 3010:3000
    volumes:
      - .:/myapp:z
      - gems:/usr/local/bundle
    env_file:
      - docker/env.web
    depends_on:
      - mysql
      - redis
  sidekiq:
    build: .
    command: 'bash -c "bundle && bundle exec sidekiq"'
    volumes:
      - .:/myapp:z
      - gems:/usr/local/bundle
    env_file:
      - docker/env.web
    depends_on:
      - mysql
      - redis
  mysql:
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
  redis:
    image: 'redis:5-alpine'
    command: redis-server
    volumes:
      - 'redis:/data'
volumes:
  mysql_data: {}
  gems:
  redis:
